---
driver:
  name: vagrant
  provider: vmware_fusion

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.2.0
    driver_config:
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
      network:
        - ["private_network", {ip: "10.10.10.135"}]
  - name: oel-7.0
    driver_config:
      box: OEL-7.2-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
      network:
        - ["private_network", {ip: "10.10.10.135"}]
  - name: oel-6.6
    driver_config:
      box: OEL-6.6
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
      network:
        - ["private_network", {ip: "10.10.10.135"}]
  - name: oel-5.8
    driver_config:
      box: OEL-5.8
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
      network:
        - ["private_network", {ip: "10.10.10.135"}]
  - name: windows-2012r2
    transport:
      name: winrm
    driver_config:
      box: win2012r2
      customize:
        memory: 3072
        cpus: 2
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
      network:
        - ["private_network", {ip: "10.10.10.135"}]
  - name: windows-8.1
    transport:
      name: winrm
    driver_config:
      box: win81x64
      customize:
        memory: 3072
        cpus: 2
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
      network:
        - ["private_network", {ip: "10.10.10.135"}]
  - name: solaris-10
    driver_config:
      box: solaris10-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
      network:
        - ["private_network", {ip: "10.10.10.135"}]
  - name: solaris-11.2
    driver_config:
      box: solaris11_2-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
      network:
        - ["private_network", {ip: "10.10.10.135"}]

suites:
  - name: wls1221
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_domain::domain]
      - recipe[fmw_domain::nodemanager]
      - recipe[fmw_domain::adminserver]
    attributes:
      fmw:
        java_home_dir:       "/usr/java/jdk1.8.0_111"
        middleware_home_dir: "/opt/oracle/middleware_1221"
        weblogic_home_dir:   "/opt/oracle/middleware_1221/wlserver"
        version:             "12.2.1.2"
      fmw_jdk:
        source_file:         "/software/jdk-8u111-linux-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/fmw_12.2.1.2.0_wls.jar"
      fmw_domain:
        databag_key:                "DEV_WLS1"
        domains_dir:                "/opt/oracle/middleware_1221/user_projects/domains"
        nodemanager_listen_address: "10.10.10.135"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10

  - name: wls1221_jrf
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_domain::domain]
      - recipe[fmw_domain::extension_jrf]
      - recipe[fmw_domain::nodemanager]
      - recipe[fmw_domain::adminserver]
    attributes:
      fmw:
        java_home_dir:       "/usr/java/jdk1.8.0_111"
        middleware_home_dir: "/opt/oracle/middleware_1221"
        weblogic_home_dir:   "/opt/oracle/middleware_1221/wlserver"
        version:             "12.2.1.2"
      fmw_jdk:
        source_file:         "/software/jdk-8u111-linux-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/fmw_12.2.1.2.0_infrastructure.jar"
        install_type:        "infra"
      fmw_domain:
        databag_key:                "DEV_WLS1"
        restricted:                 true
        domains_dir:                "/opt/oracle/middleware_1221/user_projects/domains"
        apps_dir:                   "/opt/oracle/middleware_1221/user_projects/applications"
        nodemanager_listen_address: "10.10.10.135"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10

  - name: wls1213
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_domain::domain]
      - recipe[fmw_domain::nodemanager]
      - recipe[fmw_domain::adminserver]
    attributes:
      fmw:
        java_home_dir:       "/usr/java/jdk1.8.0_40"
        middleware_home_dir: "/opt/oracle/middleware_1213"
        weblogic_home_dir:   "/opt/oracle/middleware_1213/wlserver"
      fmw_jdk:
        source_file:         "/software/jdk-8u40-linux-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/fmw_12.1.3.0.0_wls.jar"
      fmw_domain:
        databag_key:                "DEV_WLS1"
        domains_dir:                "/opt/oracle/middleware_1213/user_projects/domains"
        nodemanager_listen_address: "10.10.10.135"
        nodemanagers:
          -
            id:             "node1"
            listen_address: "10.10.10.135"
        servers:
          -
            id:             "server1"
            nodemanager:    "node1"
            listen_address: "10.10.10.135"
            listen_port:    8001
            arguments:      "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m"
          -
            id:             "server2"
            nodemanager:    "node1"
            listen_address: "10.10.10.135"
            listen_port:    8002
            arguments:      "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m"
          -
            id:             "server3"
            nodemanager:    "node1"
            listen_address: "10.10.10.135"
            listen_port:    9001
            arguments:      "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m"
        clusters:
          -
            id: "cluster1"
            members:
              - "server1"
              - "server2"
          -
            id: "cluster2"
            members:
              - "server3"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10

  - name: wls1213_sol
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_domain::domain]
      - recipe[fmw_domain::nodemanager]
      # - recipe[fmw_domain::adminserver]
    attributes:
      fmw:
        java_home_dir:       "/usr/jdk/instances/jdk1.8.0_40"
        middleware_home_dir: "/opt/oracle/middleware_1213"
        weblogic_home_dir:   "/opt/oracle/middleware_1213/wlserver"
      fmw_jdk:
        source_file:         "/software/jdk-8u40-solaris-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/fmw_12.1.3.0.0_wls.jar"
      fmw_domain:
        databag_key:                "DEV_WLS1"
        domains_dir:                "/opt/oracle/middleware_1213/user_projects/domains"
        nodemanager_listen_address: "10.10.10.135"
        nodemanagers:
          -
            id:             "node1"
            listen_address: "10.10.10.135"
        servers:
          -
            id:             "server1"
            nodemanager:    "node1"
            listen_address: "10.10.10.135"
            listen_port:    8001
            arguments:      "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m"
          -
            id:             "server2"
            nodemanager:    "node1"
            listen_address: "10.10.10.135"
            listen_port:    8002
            arguments:      "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m"
          -
            id:             "server3"
            nodemanager:    "node1"
            listen_address: "10.10.10.135"
            listen_port:    9001
            arguments:      "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m"
        clusters:
          -
            id: "cluster1"
            members:
              - "server1"
              - "server2"
          -
            id: "cluster2"
            members:
              - "server3"
    excludes:
      - windows-2012r2
      - windows-8.1
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8

  - name: wls1213_win
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::install]
      - recipe[fmw_domain::domain]
      - recipe[fmw_domain::nodemanager]
      - recipe[fmw_domain::adminserver]
    attributes:
      fmw:
        java_home_dir:       "c:\\java\\jdk1.8.0_40"
        middleware_home_dir: "c:\\oracle\\middleware_1213"
        weblogic_home_dir:   "c:\\oracle\\middleware_1213\\wlserver"
        tmp_dir:             "C:\\Users\\vagrant\\AppData\\Local\\temp"
      fmw_jdk:
        source_file:         "c:\\software\\jdk-8u40-windows-x64.exe"
      fmw_wls:
        source_file:         "c:\\software\\fmw_12.1.3.0.0_wls.jar"
      fmw_domain:
        databag_key:                "DEV_WLS1"
        domains_dir:                "c:\\oracle\\middleware_1213\\user_projects\\domains"
        apps_dir:                   "c:\\oracle\\middleware_1213\\user_projects\\applications"
        nodemanager_listen_address: "10.10.10.135"
        nodemanagers:
          -
            id:             "node1"
            listen_address: "10.10.10.135"
        servers:
          -
            id:             "server1"
            nodemanager:    "node1"
            listen_address: "10.10.10.135"
            listen_port:    8001
            arguments:      "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m"
          -
            id:             "server2"
            nodemanager:    "node1"
            listen_address: "10.10.10.135"
            listen_port:    8002
            arguments:      "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m"
          -
            id:             "server3"
            nodemanager:    "node1"
            listen_address: "10.10.10.135"
            listen_port:    9001
            arguments:      "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m"
        clusters:
          -
            id: "cluster1"
            members:
              - "server1"
              - "server2"
          -
            id: "cluster2"
            members:
              - "server3"
    excludes:
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
      - solaris-11.2
      - solaris-10

  - name: wls1213_infra
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_domain::domain]
      - recipe[fmw_domain::nodemanager]
      - recipe[fmw_domain::adminserver]
    attributes:
      fmw:
        java_home_dir:       "/usr/java/jdk1.7.0_75"
        middleware_home_dir: "/opt/oracle/middleware_1213"
        weblogic_home_dir:   "/opt/oracle/middleware_1213/wlserver"
      fmw_jdk:
        source_file:         "/software/jdk-7u75-linux-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/fmw_12.1.3.0.0_infrastructure.jar"
        install_type:        "infra"
      fmw_domain:
        databag_key:                "DEV_WLS1"
        domains_dir:                "/opt/oracle/middleware_1213/user_projects/domains"
        nodemanager_listen_address: "10.10.10.135"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10

  - name: wls1036
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_domain::domain]
      - recipe[fmw_domain::nodemanager]
      - recipe[fmw_domain::adminserver]
    attributes:
      fmw:
        java_home_dir:       "/usr/java/jdk1.7.0_75"
        middleware_home_dir: "/opt/oracle/middleware_1036"
        weblogic_home_dir:   "/opt/oracle/middleware_1036/wlserver_10.3"
        version:             "10.3.6"
      fmw_jdk:
        source_file:         "/software/jdk-7u75-linux-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/wls1036_generic.jar"
      fmw_domain:
        databag_key:                "DEV_WLS1"
        domains_dir:                "/opt/oracle/middleware_1036/user_projects/domains"
        nodemanager_listen_address: "10.10.10.135"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10