---
driver:
  name: vagrant
  # provider: vmware_fusion

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.2.0
    driver_config:
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: oel-7.0
    driver_config:
      box: OEL7_2-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["C:/software", "/software"]
  - name: oel-6.6
    driver_config:
      box: OEL6_6-x86_64_plain
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["C:/software", "/software"]
  - name: oel-5.8
    driver_config:
      box: OEL-5.8
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: windows-2012r2
    transport:
      name: winrm
    driver_config:
      box: win2012r2
      customize:
        memory: 3072
        cpus: 2
      synced_folders:
        - ["C:/software", "/software"]
  - name: windows-8.1
    transport:
      name: winrm
    driver_config:
      box: win81x64
      customize:
        memory: 3072
        cpus: 2
      synced_folders:
        - ["C:/software", "/software"]
  - name: solaris-10
    driver_config:
      box: solaris10-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: solaris-11.2
    driver_config:
      box: solaris11_2-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]


suites:
  - name: wls1221
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
    attributes:
      fmw:
        java_home_dir:       "/usr/java/jdk1.8.0_131"
        middleware_home_dir: "/opt/oracle/middleware_1221"
        version:             "12.2.1.2"
      fmw_jdk:
        source_file:         "/software/jdk-8u131-linux-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/fmw_12.2.1.2.0_wls.jar"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-10
      - solaris-11.2
  - name: wls1213
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
    attributes:
      fmw:
        java_home_dir:       "/usr/java/jdk1.8.0_131"
        middleware_home_dir: "/opt/oracle/middleware_1213"
      fmw_jdk:
        source_file:         "/software/jdk-8u131-linux-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/fmw_12.1.3.0.0_wls.jar"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-10
      - solaris-11.2
  - name: wls1213_sol
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
    attributes:
      fmw:
        java_home_dir:       "/usr/jdk/instances/jdk1.8.0_131"
        middleware_home_dir: "/opt/oracle/middleware_1213"
      fmw_jdk:
        source_file:         "/software/jdk-8u131-solaris-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/fmw_12.1.3.0.0_wls.jar"
    excludes:
      - windows-2012r2
      - windows-8.1
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
  - name: wls1213_win
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::install]
    attributes:
      fmw:
        java_home_dir:           "c:\\java\\jdk1.7.0_79"
        middleware_home_dir:     "c:\\oracle\\middleware_1213"
        version:                 "12.1.3"
        tmp_dir:                 "C:\\Users\\vagrant\\AppData\\Local\\temp"
      fmw_jdk:
        source_file:             "c:\\software\\jdk-7u79-windows-x64.exe"
      fmw_wls:
        source_file:             "c:\\software\\fmw_12.1.3.0.0_wls.jar"
    excludes:
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
      - solaris-10
      - solaris-11.2
  - name: wls1213_infra
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
    attributes:
      fmw:
        java_home_dir:       "/usr/java/jdk1.7.0_79"
        middleware_home_dir: "/opt/oracle/middleware_1213"
      fmw_jdk:
        source_file:         "/software/jdk-7u79-linux-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/fmw_12.1.3.0.0_infrastructure.jar"
        install_type:        "infra"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-10
      - solaris-11.2
  - name: wls1213_infra_win
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::install]
    attributes:
      fmw:
        java_home_dir:           "c:\\java\\jdk1.7.0_79"
        middleware_home_dir:     "c:\\oracle\\middleware_1213"
        version:                 "12.1.3"
        tmp_dir:                 "C:\\Users\\vagrant\\AppData\\Local\\temp"
      fmw_jdk:
        source_file:             "c:\\software\\jdk-7u79-windows-x64.exe"
      fmw_wls:
        source_file:             "c:\\software\\fmw_12.1.3.0.0_infrastructure.jar"
        install_type:            "infra"
    excludes:
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
      - solaris-10
      - solaris-11.2
  - name: wls1036
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
    attributes:
      fmw:
        java_home_dir:       "/usr/java/jdk1.7.0_79"
        middleware_home_dir: "/opt/oracle/middleware_1036"
        version:             "10.3.6"
      fmw_jdk:
        source_file:         "/software/jdk-7u79-linux-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/wls1036_generic.jar"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-10
      - solaris-11.2
  - name: wls1036_win
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::install]
    attributes:
      fmw:
        java_home_dir:           "c:\\java\\jdk1.7.0_79"
        middleware_home_dir:     "c:\\oracle\\middleware_1036"
        version:                 "10.3.6"
        tmp_dir:                 "C:\\Users\\vagrant\\AppData\\Local\\temp"
      fmw_jdk:
        source_file:             "c:\\software\\jdk-7u79-windows-x64.exe"
      fmw_wls:
        source_file:             "c:\\software\\wls1036_generic.jar"
    excludes:
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
      - solaris-10
      - solaris-11.2