---
driver:
  name: vagrant
  provider: vmware_fusion

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.2.0
    driver_config:
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: oel-7.0
    driver_config:
      box: OEL-7.2-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: oel-6.6
    driver_config:
      box: OEL6_6-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: oel-5.8
    driver_config:
      box: OEL-5.8
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: solaris-10
    driver_config:
      box: solaris10-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: solaris-11.2
    driver_config:
      box: solaris11_2-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: windows-2012r2
    transport:
      name: winrm
    driver_config:
      box: win2012r2
      customize:
        memory: 3072
        cpus: 2
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: windows-8.1
    transport:
      name: winrm
    driver_config:
      box: win81x64
      customize:
        memory: 3072
        cpus: 2
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]

suites:
  - name: exe
    run_list:
      - recipe[fmw_jdk::install]
    attributes:
      fmw:
        java_home_dir:    "C:/java/jdk1.8.0_111"
      fmw_jdk:
        source_file:      "/Users/edwinbiemond/software/jdk-8u111-windows-x64.exe"
    excludes:
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
      - solaris-11.2
      - solaris-10
  - name: rpm
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
    attributes:
      fmw:
        java_home_dir:    "/usr/java/jdk1.8.0_111"
      fmw_jdk:
        source_file:      "/software/jdk-8u111-linux-x64.rpm"
    excludes:
      - debian-7.2.0
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10
  - name: rpm_7
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
    attributes:
      fmw:
        java_home_dir:    "/usr/java/jdk1.7.0_79"
      fmw_jdk:
        source_file:      "/software/jdk-7u79-linux-x64.rpm"
    excludes:
      - debian-7.2.0
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10
  - name: tar
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
    attributes:
      fmw:
        java_home_dir:    "/usr/java/jdk1.8.0_111"
      fmw_jdk:
        source_file:      "/software/jdk-8u111-linux-x64.tar.gz"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10
  - name: tar_7
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
    attributes:
      fmw:
        java_home_dir:    "/usr/java/jdk1.7.0_79"
      fmw_jdk:
        source_file:      "/software/jdk-7u79-linux-x64.tar.gz"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10
  - name: tar_sol
    run_list:
      - recipe[fmw_jdk::install]
    attributes:
      fmw:
        java_home_dir:    "/usr/jdk/instances/jdk1.8.0_40"
      fmw_jdk:
        source_file:      "/software/jdk-8u40-solaris-x64.tar.gz"
    excludes:
      - windows-2012r2
      - windows-8.1
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
  - name: tar_7_sol
    run_list:
      - recipe[fmw_jdk::install]
    attributes:
      fmw:
        java_home_dir:    "/usr/jdk/instances/jdk1.7.0_75"
      fmw_jdk:
        source_file:      "/software/jdk-7u75-solaris-i586.tar.gz"
        source_x64_file:  "/software/jdk-7u75-solaris-x64.tar.gz"
    excludes:
      - windows-2012r2
      - windows-8.1
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8