require "rubygems"
require "chef"
require "yard"
YARD::Config.load_plugin 'chef'
YARD::Rake::YardocTask.new do |t|
	t.files = ['*.rb','libraries/**.rb', 'providers/*.rb','resources/*.rb','recipes/*.rb']
    #t.options = ['--debug']
end